spring:
  application.name: hiking
  datasource:
    url: jdbc:mysql://localhost:3306/hiking?autoReconnect=true&verifyServerCertificate=false
    username: hiking_app
    password: StAls2018
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  mail:
    host: smtp.gmail.com
    port: 587
    username: aaron.g.savage@gmail.com
    password: jkpmngyfoyxcknpo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
